name: Run Doctests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Build tests
        shell: cmd
        run: |
          cl /nologo /EHsc /std:c++17 /D RunTests /MDd Homework1/main.cpp /Fe:tests.exe

      - name: Run tests
        shell: cmd
        run: |
          tests.exe
